function numberEnv(name, fallback) {
  const value = Number(process.env[name]);
  return Number.isFinite(value) ? value : fallback;
}

function booleanEnv(name, fallback = false) {
  const value = process.env[name];
  if (value === undefined) return fallback;
  return ['1', 'true', 'yes', 'on'].includes(String(value).toLowerCase());
}

function categoryNumberEnv(prefix, slug, fallback) {
  const envName = `${prefix}_${slug.replace(/-/g, '_').toUpperCase()}`;
  return numberEnv(envName, fallback);
}

function listEnv(name, fallback = []) {
  const value = process.env[name];
  if (!value) return fallback;
  return value
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

function keyValueEnv(name) {
  const value = process.env[name];
  if (!value) return {};
  return Object.fromEntries(value
    .split(',')
    .map((entry) => {
      const separatorIndex = entry.includes('=') ? entry.indexOf('=') : entry.indexOf(':');
      if (separatorIndex < 1) return null;
      const key = entry.slice(0, separatorIndex).trim();
      const mappedValue = entry.slice(separatorIndex + 1).trim();
      return key && mappedValue ? [key, mappedValue] : null;
    })
    .filter(Boolean));
}

export const config = {
  databaseUrl: process.env.DATABASE_URL || 'postgres://signalrss:signalrss@localhost:5432/signalrss',
  apiPort: Number(process.env.API_PORT || 3000),
  apiRequestTimeoutMs: Number(process.env.API_REQUEST_TIMEOUT_MS || 30000),
  apiHeadersTimeoutMs: Number(process.env.API_HEADERS_TIMEOUT_MS || 10000),
  apiKeepAliveTimeoutMs: Number(process.env.API_KEEP_ALIVE_TIMEOUT_MS || 5000),
  apiMaxUrlLength: Number(process.env.API_MAX_URL_LENGTH || 2048),
  apiWriteRateLimitWindowMs: Number(process.env.API_WRITE_RATE_LIMIT_WINDOW_MS || 60000),
  apiWriteRateLimitMax: Number(process.env.API_WRITE_RATE_LIMIT_MAX || 120),
  workerPollIntervalSeconds: Number(process.env.WORKER_POLL_INTERVAL_SECONDS || 300),
  workerBatchSize: Number(process.env.WORKER_BATCH_SIZE || 50),
  ingestWindowDays: Number(process.env.INGEST_WINDOW_DAYS || 7),
  backfillConcurrency: Number(process.env.BACKFILL_CONCURRENCY || 8),
  publicBaseUrl: process.env.RSS_PUBLIC_BASE_URL || 'http://localhost:3000',
  openaiApiKey: process.env.OPENAI_API_KEY || '',
  openRouterApiKey: process.env.OPENROUTER_API_KEY || process.env.MATTERMOST_IMAGE_OPENROUTER_API_KEY || '',
  openRouterReferer: process.env.OPENROUTER_REFERER || process.env.MATTERMOST_IMAGE_OPENROUTER_REFERER || '',
  openRouterTitle: process.env.OPENROUTER_TITLE || process.env.MATTERMOST_IMAGE_OPENROUTER_TITLE || 'SignalRSS',
  openRouterRequestTimeoutMs: numberEnv('OPENROUTER_REQUEST_TIMEOUT_MS', 45000),
  groqApiKey: process.env.GROQ_API_KEY || '',
  groqBaseUrl: process.env.GROQ_BASE_URL || 'https://api.groq.com/openai/v1',
  groqRequestTimeoutMs: numberEnv('GROQ_REQUEST_TIMEOUT_MS', 45000),
  cerebrasApiKey: process.env.CEREBRAS_API_KEY || '',
  cerebrasBaseUrl: process.env.CEREBRAS_BASE_URL || 'https://api.cerebras.ai/v1',
  cerebrasRequestTimeoutMs: numberEnv('CEREBRAS_REQUEST_TIMEOUT_MS', 45000),
  sambanovaApiKey: process.env.SAMBANOVA_API_KEY || '',
  sambanovaBaseUrl: process.env.SAMBANOVA_BASE_URL || 'https://api.sambanova.ai/v1',
  sambanovaRequestTimeoutMs: numberEnv('SAMBANOVA_REQUEST_TIMEOUT_MS', 45000),
  mistralApiKey: process.env.MISTRAL_API_KEY || '',
  mistralBaseUrl: process.env.MISTRAL_BASE_URL || 'https://api.mistral.ai/v1',
  mistralRequestTimeoutMs: numberEnv('MISTRAL_REQUEST_TIMEOUT_MS', 45000),
  llmRackApiKey: process.env.LLMRACK_API_KEY || '',
  llmRackBaseUrl: process.env.LLMRACK_BASE_URL || 'https://llmrack.com/v1',
  llmRackRequestTimeoutMs: numberEnv('LLMRACK_REQUEST_TIMEOUT_MS', 45000),
  cloudflareApiToken: process.env.CLOUDFLARE_API_TOKEN || '',
  cloudflareAccountId: process.env.CLOUDFLARE_ACCOUNT_ID || '',
  cloudflareBaseUrl: process.env.CLOUDFLARE_BASE_URL || '',
  cloudflareRequestTimeoutMs: numberEnv('CLOUDFLARE_REQUEST_TIMEOUT_MS', 45000),
  githubModelsToken: process.env.GITHUB_MODELS_TOKEN || '',
  githubModelsBaseUrl: process.env.GITHUB_MODELS_BASE_URL || 'https://models.github.ai/inference',
  githubModelsRequestTimeoutMs: numberEnv('GITHUB_MODELS_REQUEST_TIMEOUT_MS', 45000),
  geminiApiKey: process.env.GEMINI_API_KEY || '',
  geminiBaseUrl: process.env.GEMINI_BASE_URL || 'https://generativelanguage.googleapis.com/v1beta/openai',
  geminiNativeBaseUrl: process.env.GEMINI_NATIVE_BASE_URL || 'https://generativelanguage.googleapis.com/v1beta',
  geminiRequestTimeoutMs: numberEnv('GEMINI_REQUEST_TIMEOUT_MS', 45000),
  gemini25ThinkingBudget: numberEnv('GEMINI_25_THINKING_BUDGET', 0),
  gemini3ThinkingLevel: process.env.GEMINI_3_THINKING_LEVEL || 'LOW',
  nvidiaApiKey: process.env.NVIDIA_API_KEY || process.env.MATTERMOST_IMAGE_NVIDIA_API_KEY || '',
  nvidiaBaseUrl: process.env.NVIDIA_BASE_URL || 'https://integrate.api.nvidia.com',
  nvidiaRequestTimeoutMs: numberEnv('NVIDIA_REQUEST_TIMEOUT_MS', 45000),
  embeddingModel: process.env.EMBEDDING_MODEL || 'text-embedding-3-small',
  classifierBatchSize: Number(process.env.CLASSIFIER_BATCH_SIZE || 50),
  classifierPollIntervalSeconds: Number(process.env.CLASSIFIER_POLL_INTERVAL_SECONDS || 300),
  classifierTopCategories: Number(process.env.CLASSIFIER_TOP_CATEGORIES || 3),
  classifierMinConfidence: Number(process.env.CLASSIFIER_MIN_CONFIDENCE || 0.18),
  classifierAiMinConfidence: Number(process.env.CLASSIFIER_AI_MIN_CONFIDENCE || 0.30),
  classifierMinMargin: numberEnv('CLASSIFIER_MIN_MARGIN', 0),
  classifierMinConfidenceByCategory: {
    'artificial-intelligence': Number(process.env.CLASSIFIER_AI_MIN_CONFIDENCE || 0.30),
    'cloud-infrastructure': categoryNumberEnv('CLASSIFIER_MIN_CONFIDENCE', 'cloud-infrastructure', 0.26),
    'automotive-mobility': categoryNumberEnv('CLASSIFIER_MIN_CONFIDENCE', 'automotive-mobility', 0.29),
    gaming: categoryNumberEnv('CLASSIFIER_MIN_CONFIDENCE', 'gaming', 0.24),
    'fintech-crypto': categoryNumberEnv('CLASSIFIER_MIN_CONFIDENCE', 'fintech-crypto', 0.28),
    'crypto-web3': categoryNumberEnv('CLASSIFIER_MIN_CONFIDENCE', 'crypto-web3', 0.34),
    'software-development': categoryNumberEnv('CLASSIFIER_MIN_CONFIDENCE', 'software-development', 0.22),
  },
  classifierMinMarginByCategory: {
    'cloud-infrastructure': categoryNumberEnv('CLASSIFIER_MIN_MARGIN', 'cloud-infrastructure', 0.02),
    'automotive-mobility': categoryNumberEnv('CLASSIFIER_MIN_MARGIN', 'automotive-mobility', 0.01),
    gaming: categoryNumberEnv('CLASSIFIER_MIN_MARGIN', 'gaming', 0.01),
    'fintech-crypto': categoryNumberEnv('CLASSIFIER_MIN_MARGIN', 'fintech-crypto', 0.02),
    'crypto-web3': categoryNumberEnv('CLASSIFIER_MIN_MARGIN', 'crypto-web3', 0.02),
    'software-development': categoryNumberEnv('CLASSIFIER_MIN_MARGIN', 'software-development', 0.01),
  },
  classifierCategoryGuards: {
    cybersecurity: {
      enabled: booleanEnv('CLASSIFIER_GUARD_CYBERSECURITY_ENABLED', true),
      requireRequiredTermsAlways: true,
      strictExcludesEnabled: booleanEnv('CLASSIFIER_GUARD_CYBERSECURITY_STRICT_EXCLUDES', true),
      alwaysExcludedTerms: [
        'alien files',
        'aliens.gov',
        'declassified ufo',
        'extraterrestrial',
        'ovnis',
        'uap documents',
        'ufo',
        'ufo files',
        'war.gov/ufo',
        '未確認異常現象',
        '解密 ufo',
      ],
      excludedTerms: [
        'earnings',
        'financial results',
        'game pass',
        'gaming',
        'market close',
        'market opens',
        'stock market',
      ],
      requiredTerms: [
        'account takeover',
        'breach',
        'bug bounty',
        'ciso',
        'credential',
        'credentials',
        'cve',
        'cyber attack',
        'cyberattack',
        'cybersecurity',
        'data breach',
        'data leak',
        'ddos',
        'exploit',
        'exploited',
        'firewall',
        'hack',
        'hacked',
        'hacker',
        'hackers',
        'infosec',
        'information leak',
        'intrusion',
        'malware',
        'phishing',
        'ransomware',
        'security flaw',
        'security incident',
        'security patch',
        'spyware',
        'threat actor',
        'vulnerability',
        'zero-day',
        'zero day',
        'サイバー',
        'セキュリティ',
        'ハッカー',
        '不正アクセス',
        '情報流出',
        '漏洞',
        '网络安全',
        '黑客',
        '개인정보 유출',
        '보안',
        '사이버',
        '해킹',
      ],
    },
    gaming: {
      enabled: booleanEnv('CLASSIFIER_GUARD_GAMING_ENABLED', true),
      strictExcludesEnabled: booleanEnv('CLASSIFIER_GUARD_GAMING_STRICT_EXCLUDES', true),
      excludedTerms: [
        'arrest',
        'arrested',
        'betting',
        'casino',
        'crackdown',
        'gambling',
        'illegal gambling',
        'lottery',
        'online gambling',
        'police',
        'sports betting',
        'wager',
        'wagering',
      ],
      requiredTerms: [
        'call of duty',
        'console',
        'discord',
        'game pass',
        'game studio',
        'gameplay',
        'gaming pc',
        'gta',
        'nintendo',
        'playstation',
        'ps5',
        'steam',
        'switch',
        'unreal engine',
        'video game',
        'videogame',
        'xbox',
        'ゲーム',
        '任天堂',
      ],
    },
    'fintech-crypto': {
      enabled: booleanEnv('CLASSIFIER_GUARD_FINTECH_CRYPTO_ENABLED', true),
      requireRequiredTermsAlways: true,
      strictExcludesEnabled: booleanEnv('CLASSIFIER_GUARD_FINTECH_CRYPTO_STRICT_EXCLUDES', true),
      alwaysExcludedTerms: [
        'app themes',
        'custom themes',
        'data center outage',
        'data centre outage',
        'cybersecurity company',
        'free channel',
        'firewall demand',
        'live only at',
        'prime video',
        'security networking',
        'streaming',
        'techcrunch disrupt',
        'whatsapp plus',
        '방화벽',
        '보안·네트워크',
        '사이버보안 기업',
      ],
      excludedTerms: [
        'disney',
        'instagram',
        'netflix',
        'series a',
        'social app',
        'social media',
        'tiktok',
        'video clips',
      ],
      requiredTerms: [
        'aml',
        'asset management',
        'bank',
        'banking',
        'bargeld',
        'bitcoin',
        'blockchain',
        'broker',
        'brokerage',
        'card issuer',
        'cash',
        'coinbase',
        'crypto',
        'cryptocurrency',
        'debit card',
        'digital asset',
        'digital bank',
        'ethereum',
        'exchange',
        'fintech',
        'fund manager',
        'investment app',
        'kakao pay',
        'kyc',
        'lending',
        'loan',
        'merchant payment',
        'money',
        'neobank',
        'payment',
        'paytm',
        'remittance',
        'securities',
        'stablecoin',
        'stock trading',
        'token',
        'tokenization',
        'trade republic',
        'trading',
        'wallet',
        'wealth management',
        'banco',
        'banca',
        'banque',
        'paiement',
        'bezahlen',
        'd払い',
        'マネーフォワード',
        'ポイント',
        '決済',
        '金融',
        '銀行',
        '支付',
        '金融',
        '银行',
        '证券',
        '가상자산',
        '금융',
        '은행',
        '증권',
      ],
    },
    'crypto-web3': {
      enabled: booleanEnv('CLASSIFIER_GUARD_CRYPTO_WEB3_ENABLED', true),
      requireRequiredTermsAlways: true,
      strictExcludesEnabled: booleanEnv('CLASSIFIER_GUARD_CRYPTO_WEB3_STRICT_EXCLUDES', true),
      alwaysExcludedTerms: [
        'ai-native',
        'arr',
        'cuts workforce',
        'data center outage',
        'data centre overheated',
        'demo users',
        'earnings',
        'employees',
        'emplois',
        'gross profit',
        'headcount',
        'job',
        'job cuts',
        'jobs',
        'k-drama',
        'k-pop',
        'layoff',
        'layoffs',
        'licencie',
        'licenciement',
        'lost $',
        'presale',
        'revenue',
        'save costs',
        'stage momentum',
        'workforce',
        'chiffre d’affaires',
        "chiffre d'affaires",
        'remplacer',
        '従業員',
        '解雇',
      ],
      excludedTerms: [
        'after hours',
        'ai agent',
        'anthropic',
        'arr',
        'aws',
        'bedrock',
        'cloud',
        'compute futures',
        'data center',
        'data centre',
        'datacenter',
        'earnings',
        'fanduel',
        'financial services solutions',
        'gross profit',
        'holding firm',
        'k-drama',
        'k-pop',
        'revenue',
        'shares',
        'stock',
        'valuation',
      ],
      requiredTerms: [
        'avalanche',
        'base mainnet',
        'binance',
        'bitcoin',
        'blockchain',
        'btc',
        'chainlink',
        'circle',
        'coinbase',
        'consensus conference',
        'crypto',
        'cryptocurrency',
        'dao',
        'decentralized finance',
        'defi',
        'digital asset',
        'digital assets',
        'ethereum',
        'layer 2',
        'mcp tools on base',
        'nft',
        'on-chain',
        'onchain',
        'oracle network',
        'polygon',
        'redstone',
        'ripple',
        'rollup',
        'smart contract',
        'solana',
        'stablecoin',
        'staking',
        'token',
        'tokenisation',
        'tokenised',
        'tokenization',
        'tokenized',
        'usdc',
        'usdt',
        'virtual asset',
        'wallet',
        'web 3',
        'web3',
        'xrp',
        'ステーブルコイン',
        'トークン',
        'ビットコイン',
        'ブロックチェーン',
        '仮想通貨',
        '暗号資産',
        'オンチェーン',
        'イーサリアム',
        '토큰',
        '블록체인',
        '비트코인',
        '서클',
        '스테이블코인',
        '암호화폐',
        '온체인',
        '이더리움',
        '가상자산',
        '代币',
        '以太坊',
        '加密货币',
        '区块链',
        '比特币',
        '稳定币',
        '虚拟资产',
        '链上',
      ],
    },
    'automotive-mobility': {
      enabled: booleanEnv('CLASSIFIER_GUARD_AUTOMOTIVE_MOBILITY_ENABLED', true),
      strictExcludesEnabled: booleanEnv('CLASSIFIER_GUARD_AUTOMOTIVE_STRICT_EXCLUDES', true),
      alwaysExcludedTerms: [
        'advertising ecosystem',
        'ai-powered carbon',
        'arrow electronics partners with motorola solutions',
        'astera speaks softly and carries a big switch',
        'carbon emissions database',
        'data center',
        'data centre',
        'datacenter',
        'datacentre',
        'digital transformation',
        'green hydrogen',
        'hvac',
        'in-home elder care',
        'interpack',
        'offshore power grid',
        'pharmaceutical',
        'solar generation',
        'solar-tracking',
        'solar demand',
        'sovereign ai',
        'storage microgrid',
      ],
      excludedTerms: [
        'xbox',
        'game pass',
        'gaming copilot',
        'game console',
        'games console',
        'console',
        'copilot',
        'microsoft 365 copilot',
        'copilot app',
        'copilot ai',
        'productivity copilot',
        'advertising ecosystem',
        'ai-powered carbon',
        'carbon emissions database',
        'data center',
        'data centre',
        'datacenter',
        'datacentre',
        'digital transformation',
        'green hydrogen',
        'hvac',
        'in-home elder care',
        'interpack',
        'mobileaction',
        'offshore power grid',
        'pharmaceutical',
        'solar demand',
        'sovereign ai',
      ],
      requiredTerms: [
        'adas',
        'android auto',
        'auto',
        'automotive',
        'battery',
        'batteries',
        'byd',
        'car',
        'carplay',
        'charging',
        'driver',
        'driving',
        'e-bike',
        'electric vehicle',
        'ev',
        'fleet',
        'hybrid',
        'mobility',
        'motorcycle',
        'ride hailing',
        'road',
        'robotaxi',
        'tesla',
        'transport',
        'truck',
        'vehicle',
        'volkswagen',
        'xpeng',
        'assisted driving',
        'autonomous driving',
        'battery electric',
        'bev',
        'blade battery',
        'car maker',
        'carmaker',
        'commercial vehicle',
        'connected car',
        'electric car',
        'electric mobility',
        'electric truck',
        'electrified vehicle',
        'ev battery',
        'ev charging',
        'fast charging',
        'lidar',
        'mpv',
        'new energy vehicle',
        'passenger vehicle',
        'plug-in hybrid',
        'range extender',
        'self-driving',
        'smart mobility',
        'solid-state battery',
        'steer-by-wire',
        'two-wheeler',
        'urban air mobility',
        'vehicle software',
      ],
    },
    'startups-venture-capital': {
      enabled: booleanEnv('CLASSIFIER_GUARD_STARTUPS_VENTURE_CAPITAL_ENABLED', true),
      strictExcludesEnabled: booleanEnv('CLASSIFIER_GUARD_STARTUPS_VENTURE_CAPITAL_STRICT_EXCLUDES', true),
      alwaysExcludedTerms: [
        'before space runs out',
        'daily horoscope',
        'exhibit at',
        'get 50% off',
        'horoscope',
        'live only at',
        'lock in 50% off',
        'questions will be answered',
        'second pass',
        'second ticket',
        'techcrunch disrupt',
        'token fortune',
        '토큰운세',
        '띠별',
        '운세',
        'connections hints',
        'connections answers',
        'nyt connections',
        'wordle',
        'game #',
      ],
      excludedTerms: [
        'coupon',
        'daily horoscope',
        'deal',
        'discount',
        'game #',
        'game pass',
        'gaming',
        'horoscope',
        'hints and answers',
        'market close',
        'market opens',
        'market rally',
        'market update',
        'nyt connections',
        'pass to techcrunch disrupt',
        'shares closed',
        'stock market',
        'stocks rise',
        'stocks slid',
        'token fortune',
        'wordle',
        '토큰운세',
        '띠별',
        '운세',
        '中概股',
        '创业板指',
        '恒指',
        '收盘涨',
        '收盘跌',
        '美股',
        '涨超',
        '跌超',
      ],
      requiredTerms: [
        'accelerator',
        'acquisition',
        'acquires',
        'angel investor',
        'backed by',
        'buyout',
        'cap table',
        'capital raise',
        'corporate venture',
        'debut on stock markets',
        'exit',
        'funding',
        'funding round',
        'growth equity',
        'incubator',
        'ipo',
        'launches fund',
        'm&a',
        'merger',
        'pre-seed',
        'private equity',
        'raises',
        'seed round',
        'series a',
        'series b',
        'series c',
        'spac',
        'startup',
        'start-up',
        'term sheet',
        'unicorn',
        'valuation',
        'venture',
        'venture capital',
        'vc',
        'vc firm',
        'vc fund',
        '投资',
        '融资',
        '初创',
        '创投',
        '创业公司',
        '创业企业',
        '스타트업',
        '투자',
        '벤처',
        '并购',
        '收购',
        '上市',
      ],
    },
    'science-research': {
      enabled: booleanEnv('CLASSIFIER_GUARD_SCIENCE_RESEARCH_ENABLED', true),
      requireRequiredTermsAlways: true,
      strictExcludesEnabled: booleanEnv('CLASSIFIER_GUARD_SCIENCE_RESEARCH_STRICT_EXCLUDES', true),
      alwaysExcludedTerms: [
        'astro',
        'backup',
        'career & money report',
        'codex',
        'cpu boost',
        'business update',
        'data center',
        'data centre',
        'datacenter',
        'datacentre',
        'desktop app',
        'desktop environment',
        'docking station',
        'financial results',
        'file space',
        'fotografie-wettbewerb',
        'fixed wireless access',
        'git for knowledge',
        'hdd',
        'internet speed',
        'market',
        'market rally',
        'pc build',
        'perplexity personal computer',
        'power supply',
        'qclaw',
        'r&d spending',
        'rtx',
        'siri ai delay',
        'ssd',
        'stock',
        'stock market',
        'vitesse de connexion internet',
        'vran',
        'wayland',
        'windows 11',
        'win11',
        '恒生科技指数',
        '盘中涨',
      ],
      excludedTerms: [
        'app is now available',
        'cloud infrastructure',
        'compensation',
        'data center',
        'data centre',
        'datacenter',
        'datacentre',
        'desktop app',
        'earnings',
        'financial results',
        'file space',
        'funding',
        'hdd',
        'ipo',
        'manufacturing',
        'market',
        'personal computer',
        'profit',
        'r&d centre',
        'r&d center',
        'raises',
        'release',
        'revenue',
        'series a',
        'series b',
        'series c',
        'shares',
        'startup',
        'stock',
        'valuation',
        'venture',
        'windows',
        'windows 11',
        'win11',
        '投资',
        '融资',
        '创业',
        '上市',
        '涨超',
      ],
      requiredTerms: [
        'academic',
        'academic research',
        'advanced r&d',
        'astronomer',
        'astronomy',
        'bioengineering',
        'biogas',
        'biotech',
        'biology',
        'chemistry',
        'clinical',
        'co2',
        'cosmic',
        'dark matter',
        'drug discovery',
        'experiment',
        'geology',
        'genome',
        'laboratory',
        'lab',
        'material science',
        'medicine',
        'microplastic',
        'molecule',
        'nasa',
        'nature',
        'neuroscience',
        'ocean',
        'physics',
        'planet',
        'protein',
        'quantum',
        'research breakthrough',
        'research lab',
        'research laboratory',
        'research reactor',
        'researcher',
        'scientific',
        'scientists',
        'solar storm',
        'spacecraft',
        'telescope',
        'trial',
        '학회',
        '과학',
        '단백질',
        '바이오',
        '생명',
        '양자',
        '우주',
        '임상',
        '항공우주',
        '医学',
        '基因',
        '天文',
        '宇宙',
        '物理',
        '生物',
        '科学',
        '量子',
        '航天',
        '蛋白',
        '臨床',
        '医学',
        '宇宙',
        '物理',
        '生物',
        '科学',
        '量子',
      ],
    },
    'policy-regulation': {
      enabled: booleanEnv('CLASSIFIER_GUARD_POLICY_REGULATION_ENABLED', true),
      requireRequiredTermsAlways: true,
      strictExcludesEnabled: booleanEnv('CLASSIFIER_GUARD_POLICY_REGULATION_STRICT_EXCLUDES', true),
      alwaysExcludedTerms: [
        'best vpn',
        'casino',
        'daily horoscope',
        'fantasy sports',
        'game #',
        'get 50% off',
        'horoscope',
        'market gains',
        'market rally',
        'nyt connections',
        'pass to techcrunch disrupt',
        'review gating',
        'review routing',
        'second pass',
        'sports betting',
        'stock market',
        'techcrunch disrupt',
        't&d 2026',
        'agriculture',
        'aliens',
        'aliens.gov',
        'clinical trials',
        'crop',
        'health policy',
        'international order',
        'labor conflict',
        'labour conflict',
        'oda',
        'patient data',
        'plastic container',
        'public institution',
        'rice',
        'ufo',
        'ufo files',
        'world war',
        '공공기관',
        '영농형',
        '농지',
        'vue d’ensemble',
        'wordle',
        '노사 갈등',
        '농촌',
        '쌀',
        '토큰운세',
        '띠별',
        '운세',
        '收盘涨',
        '收盘跌',
        '涨超',
        '跌超',
      ],
      excludedTerms: [
        'coupon',
        'deal',
        'discount',
        'earnings',
        'financial results',
        'game pass',
        'market close',
        'market opens',
        'market update',
        'shares closed',
        'stocks rise',
        'stocks slid',
      ],
      requiredTerms: [
        'accountability',
        'age checks',
        'age verification',
        'ai act',
        'ai governance',
        'algorithmic transparency',
        'antitrust',
        'ban',
        'bill',
        'biometric',
        'censorship',
        'child safety',
        'competition authority',
        'compliance',
        'copyright',
        'court',
        'data protection',
        'digital markets',
        'dsa',
        'dma',
        'encryption',
        'eu law',
        'export control',
        'export controls',
        'fcc',
        'ftc',
        'gdpr',
        'investigation',
        'judicial review',
        'lawsuit',
        'legal dispute',
        'liability',
        'license',
        'market structure bill',
        'moderation',
        'noyb',
        'privacy',
        'regulation',
        'regulator',
        'regulatory',
        'sanction',
        'sanctions',
        'social media addiction',
        'supreme court',
        'tariff',
        'transparency',
        'uk age checks',
        'vpn crackdown',
        'white house',
        '개인정보',
        '규제',
        '법원',
        '소송',
        '저작권',
        '프라이버시',
        '监管',
        '法规',
        '法律',
        '诉讼',
        '隐私',
        '监管',
        '政策',
        '著作权',
      ],
      requiredTermGroups: [
        [
          'ai',
          'algorithm',
          'algorithmic',
          'app',
          'app store',
          'biometric',
          'bitcoin',
          'blockchain',
          'broadband',
          'cloud',
          'crypto',
          'cyber',
          'data',
          'digital',
          'drone',
          'encryption',
          'internet',
          'online',
          'platform',
          'privacy',
          'semiconductor',
          'social media',
          'software',
          'space systems',
          'surveillance',
          'tech',
          'technology',
          'tokenization',
          'virtual asset',
          '가상자산',
          '개인정보',
          '디지털',
          '데이터',
          '平台',
          '互联网',
          '数据',
          '数字',
          '隐私',
        ],
      ],
    },
  },
  classifierRunUntilEmpty: process.env.CLASSIFIER_RUN_UNTIL_EMPTY === 'true',
  classifierMaxSummaryChars: Number(process.env.CLASSIFIER_MAX_SUMMARY_CHARS || 1000),
  classifierMaxContentChars: Number(process.env.CLASSIFIER_MAX_CONTENT_CHARS || 500),
  classifierMaxInputChars: Number(process.env.CLASSIFIER_MAX_INPUT_CHARS || 3000),
  clusterBatchSize: Number(process.env.CLUSTER_BATCH_SIZE || 200),
  clusterPollIntervalSeconds: Number(process.env.CLUSTER_POLL_INTERVAL_SECONDS || 300),
  clusterSimilarityThreshold: numberEnv('CLUSTER_SIMILARITY_THRESHOLD', 0.65),
  clusterAiSimilarityThreshold: numberEnv('CLUSTER_AI_SIMILARITY_THRESHOLD', 0.78),
  clusterSimilarityThresholds: {
    'artificial-intelligence': numberEnv('CLUSTER_AI_SIMILARITY_THRESHOLD', 0.78),
    cybersecurity: numberEnv('CYBERSECURITY_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    'cloud-infrastructure': numberEnv('CLOUD_INFRASTRUCTURE_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    'automotive-mobility': numberEnv('AUTOMOTIVE_MOBILITY_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    semiconductors: numberEnv('SEMICONDUCTORS_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    'software-development': numberEnv('SOFTWARE_DEVELOPMENT_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    'consumer-electronics': numberEnv('CONSUMER_ELECTRONICS_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    gaming: numberEnv('GAMING_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    'fintech-crypto': numberEnv('FINTECH_CRYPTO_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    'crypto-web3': numberEnv('CRYPTO_WEB3_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    'enterprise-technology': numberEnv('ENTERPRISE_TECHNOLOGY_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    'startups-venture-capital': numberEnv('STARTUPS_VENTURE_CAPITAL_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    'science-research': numberEnv('SCIENCE_RESEARCH_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
    'policy-regulation': numberEnv('POLICY_REGULATION_CLUSTER_SIMILARITY_THRESHOLD', 0.78),
  },
  clusterCategorySlug: process.env.CLUSTER_CATEGORY_SLUG || '',
  clusterWindowDays: Number(process.env.CLUSTER_WINDOW_DAYS || 7),
  clusterRunUntilEmpty: process.env.CLUSTER_RUN_UNTIL_EMPTY === 'true',
  clusterMergeBatchSize: Number(process.env.CLUSTER_MERGE_BATCH_SIZE || 50),
  clusterMergePollIntervalSeconds: Number(process.env.CLUSTER_MERGE_POLL_INTERVAL_SECONDS || 300),
  clusterMergeSimilarityThreshold: Number(process.env.CLUSTER_MERGE_SIMILARITY_THRESHOLD || 0.82),
  clusterMergeCategorySlug: process.env.CLUSTER_MERGE_CATEGORY_SLUG || 'artificial-intelligence',
  clusterMergeWindowDays: Number(process.env.CLUSTER_MERGE_WINDOW_DAYS || 7),
  clusterMergeRunUntilStable: process.env.CLUSTER_MERGE_RUN_UNTIL_STABLE === 'true',
  p0AdjudicationModel: process.env.P0_ADJUDICATION_MODEL || 'gpt-5-nano',
  p0AdjudicationBatchSize: Number(process.env.P0_ADJUDICATION_BATCH_SIZE || 12),
  p0AdjudicationPollIntervalSeconds: Number(process.env.P0_ADJUDICATION_POLL_INTERVAL_SECONDS || 300),
  p0AdjudicationWindowHours: Number(process.env.P0_ADJUDICATION_WINDOW_HOURS || 168),
  p0AdjudicationCategorySlug: process.env.P0_ADJUDICATION_CATEGORY_SLUG || 'artificial-intelligence',
  p0AdjudicationMinCentroidSimilarity: Number(process.env.P0_ADJUDICATION_MIN_CENTROID_SIMILARITY || 0.70),
  p0AdjudicationMaxCentroidSimilarity: Number(process.env.P0_ADJUDICATION_MAX_CENTROID_SIMILARITY || 0.82),
  p0AdjudicationMinArticleSimilarity: Number(process.env.P0_ADJUDICATION_MIN_ARTICLE_SIMILARITY || 0.72),
  p0AdjudicationMergeConfidence: Number(process.env.P0_ADJUDICATION_MERGE_CONFIDENCE || 0.70),
  p1AdjudicationModel: process.env.P1_ADJUDICATION_MODEL || 'gpt-5-nano',
  p1AdjudicationBatchSize: Number(process.env.P1_ADJUDICATION_BATCH_SIZE || 20),
  p1AdjudicationPollIntervalSeconds: Number(process.env.P1_ADJUDICATION_POLL_INTERVAL_SECONDS || 300),
  p1AdjudicationWindowHours: Number(process.env.P1_ADJUDICATION_WINDOW_HOURS || 168),
  p1AdjudicationCategorySlug: process.env.P1_ADJUDICATION_CATEGORY_SLUG || 'artificial-intelligence',
  p1AdjudicationP1P1MinCentroidSimilarity: Number(process.env.P1_ADJUDICATION_P1P1_MIN_CENTROID_SIMILARITY || 0.72),
  p1AdjudicationP1P0MinCentroidSimilarity: Number(process.env.P1_ADJUDICATION_P1P0_MIN_CENTROID_SIMILARITY || 0.70),
  p1AdjudicationMaxCentroidSimilarity: Number(process.env.P1_ADJUDICATION_MAX_CENTROID_SIMILARITY || 0.82),
  p1AdjudicationMinArticleSimilarity: Number(process.env.P1_ADJUDICATION_MIN_ARTICLE_SIMILARITY || 0.74),
  p1AdjudicationMergeConfidence: Number(process.env.P1_ADJUDICATION_MERGE_CONFIDENCE || 0.70),
  p2AdjudicationModel: process.env.P2_ADJUDICATION_MODEL || 'gpt-5-nano',
  p2AdjudicationBatchSize: Number(process.env.P2_ADJUDICATION_BATCH_SIZE || 20),
  p2AdjudicationPollIntervalSeconds: Number(process.env.P2_ADJUDICATION_POLL_INTERVAL_SECONDS || 300),
  p2AdjudicationWindowHours: Number(process.env.P2_ADJUDICATION_WINDOW_HOURS || 168),
  p2AdjudicationCategorySlug: process.env.P2_ADJUDICATION_CATEGORY_SLUG || 'artificial-intelligence',
  p2AdjudicationP2P2MinCentroidSimilarity: Number(process.env.P2_ADJUDICATION_P2P2_MIN_CENTROID_SIMILARITY || 0.72),
  p2AdjudicationP2P1MinCentroidSimilarity: Number(process.env.P2_ADJUDICATION_P2P1_MIN_CENTROID_SIMILARITY || 0.70),
  p2AdjudicationP2P0MinCentroidSimilarity: Number(process.env.P2_ADJUDICATION_P2P0_MIN_CENTROID_SIMILARITY || 0.70),
  p2AdjudicationMaxCentroidSimilarity: Number(process.env.P2_ADJUDICATION_MAX_CENTROID_SIMILARITY || 0.82),
  p2AdjudicationMinArticleSimilarity: Number(process.env.P2_ADJUDICATION_MIN_ARTICLE_SIMILARITY || 0.72),
  p2AdjudicationMergeConfidence: Number(process.env.P2_ADJUDICATION_MERGE_CONFIDENCE || 0.70),
  p3AdjudicationModel: process.env.P3_ADJUDICATION_MODEL || 'gpt-5-nano',
  p3AdjudicationBatchSize: Number(process.env.P3_ADJUDICATION_BATCH_SIZE || 20),
  p3AdjudicationPollIntervalSeconds: Number(process.env.P3_ADJUDICATION_POLL_INTERVAL_SECONDS || 300),
  p3AdjudicationWindowHours: Number(process.env.P3_ADJUDICATION_WINDOW_HOURS || 168),
  p3AdjudicationCategorySlug: process.env.P3_ADJUDICATION_CATEGORY_SLUG || 'artificial-intelligence',
  p3AdjudicationP3P3MinCentroidSimilarity: Number(process.env.P3_ADJUDICATION_P3P3_MIN_CENTROID_SIMILARITY || 0.72),
  p3AdjudicationP3P2MinCentroidSimilarity: Number(process.env.P3_ADJUDICATION_P3P2_MIN_CENTROID_SIMILARITY || 0.70),
  p3AdjudicationP3P1MinCentroidSimilarity: Number(process.env.P3_ADJUDICATION_P3P1_MIN_CENTROID_SIMILARITY || 0.70),
  p3AdjudicationP3P0MinCentroidSimilarity: Number(process.env.P3_ADJUDICATION_P3P0_MIN_CENTROID_SIMILARITY || 0.70),
  p3AdjudicationMaxCentroidSimilarity: Number(process.env.P3_ADJUDICATION_MAX_CENTROID_SIMILARITY || 0.82),
  p3AdjudicationMinArticleSimilarity: Number(process.env.P3_ADJUDICATION_MIN_ARTICLE_SIMILARITY || 0.72),
  p3AdjudicationMergeConfidence: Number(process.env.P3_ADJUDICATION_MERGE_CONFIDENCE || 0.70),
  impactModel: process.env.IMPACT_MODEL || 'gpt-5-nano',
	  impactModelFallbacks: listEnv('IMPACT_MODEL_FALLBACKS', [
	    'mistral:mistral-small-latest',
	    'nvidia:openai/gpt-oss-120b',
	    'github:openai/gpt-4.1-mini',
	    'github:openai/gpt-4o-mini',
	    'groq:openai/gpt-oss-120b',
    'groq:llama-3.3-70b-versatile',
    'groq:openai/gpt-oss-20b',
	    'openrouter:openai/gpt-oss-120b:free',
    'openrouter:nvidia/nemotron-3-super-120b-a12b:free',
	    'sambanova:gpt-oss-120b',
	    'gemini:gemini-2.5-flash',
	    'cloudflare:@cf/openai/gpt-oss-120b',
    'cerebras:llama3.1-8b',
    'llmrack:qwen-2.5-7b',
    `openai:${process.env.IMPACT_MODEL || 'gpt-5-nano'}`,
  ]),
  impactMaxOutputTokens: numberEnv('IMPACT_MAX_OUTPUT_TOKENS', 2200),
  impactBatchSize: Number(process.env.IMPACT_BATCH_SIZE || 25),
  impactBatchesPerTick: Number(process.env.IMPACT_BATCHES_PER_TICK || 1),
  categoryImpactCategoriesPerTick: numberEnv('CATEGORY_IMPACT_CATEGORIES_PER_TICK', 3),
  impactPollIntervalSeconds: Number(process.env.IMPACT_POLL_INTERVAL_SECONDS || 300),
  impactWindowHours: Number(process.env.IMPACT_WINDOW_HOURS || 168),
  impactMinPublishedAt: process.env.IMPACT_MIN_PUBLISHED_AT || '',
  impactCategorySlug: process.env.IMPACT_CATEGORY_SLUG || 'artificial-intelligence',
  impactRunUntilEmpty: process.env.IMPACT_RUN_UNTIL_EMPTY === 'true',
  impactJobStaleMinutes: Number(process.env.IMPACT_JOB_STALE_MINUTES || 30),
  impactJobRetryMinutes: Number(process.env.IMPACT_JOB_RETRY_MINUTES || 10),
  impactJobMaxAttempts: Number(process.env.IMPACT_JOB_MAX_ATTEMPTS || 5),
  impactRunStaleMinutes: Number(process.env.IMPACT_RUN_STALE_MINUTES || 30),
  p0BriefingModel: process.env.P0_BRIEFING_MODEL || 'gpt-5-nano',
	  briefingModelFallbacks: listEnv('BRIEFING_MODEL_FALLBACKS', [
	    'mistral:mistral-small-latest',
	    'nvidia:openai/gpt-oss-120b',
	    'github:openai/gpt-4.1-mini',
	    'github:openai/gpt-4o-mini',
	    'github:mistral-ai/mistral-small-2503',
	    'github:meta/meta-llama-3.1-8b-instruct',
	    'groq:openai/gpt-oss-120b',
    'groq:llama-3.3-70b-versatile',
    'groq:openai/gpt-oss-20b',
	    'openrouter:openai/gpt-oss-120b:free',
    'openrouter:nvidia/nemotron-3-super-120b-a12b:free',
	    'gemini:gemini-3-flash-preview',
	    'gemini:gemma-4-31b-it',
	    'sambanova:gpt-oss-120b',
	    'cloudflare:@cf/openai/gpt-oss-120b',
    'cerebras:llama3.1-8b',
    'llmrack:qwen-2.5-7b',
    `openai:${process.env.P0_BRIEFING_MODEL || 'gpt-5-nano'}`,
  ]),
  p0BriefingBatchSize: Number(process.env.P0_BRIEFING_BATCH_SIZE || 10),
  p0BriefingPollIntervalSeconds: Number(process.env.P0_BRIEFING_POLL_INTERVAL_SECONDS || 300),
  p0BriefingWindowHours: Number(process.env.P0_BRIEFING_WINDOW_HOURS || 168),
  briefingOutputLanguage: process.env.BRIEFING_OUTPUT_LANGUAGE || 'Spanish',
  briefingVersionSuffix: process.env.BRIEFING_VERSION_SUFFIX || '',
  briefingCategoryGuidanceJson: process.env.BRIEFING_CATEGORY_GUIDANCE_JSON || '',
  briefingMinPublishedAt: process.env.BRIEFING_MIN_PUBLISHED_AT || '',
  briefingClaimStaleMinutes: Number(process.env.BRIEFING_CLAIM_STALE_MINUTES || 15),
  briefingStartupClaimCleanupMinutes: numberEnv('BRIEFING_STARTUP_CLAIM_CLEANUP_MINUTES', 2),
  briefingOpenAiFallbackLevels: listEnv('BRIEFING_OPENAI_FALLBACK_LEVELS', ['P0', 'P1', 'P2', 'P3'])
    .map((level) => level.toUpperCase()),
  llmCooldownEnabled: booleanEnv('LLM_COOLDOWN_ENABLED', true),
  llmSambanovaFreeRpm: numberEnv('LLM_SAMBANOVA_FREE_RPM', 20),
  llmGeminiRpm: numberEnv('LLM_GEMINI_RPM', 5),
  llmMistralRpm: numberEnv('LLM_MISTRAL_RPM', 6),
  llmRackRpm: numberEnv('LLM_LLMRACK_RPM', 10),
  llmRackTokensPerDay: numberEnv('LLM_LLMRACK_TPD', 10000),
  llmRackImpactMaxBatchSize: numberEnv('LLM_LLMRACK_IMPACT_MAX_BATCH_SIZE', 2),
  llmRackBriefingMaxBatchSize: numberEnv('LLM_LLMRACK_BRIEFING_MAX_BATCH_SIZE', 1),
  llmGithubLowRpm: numberEnv('LLM_GITHUB_LOW_RPM', 15),
  llmGithubImpactMaxBatchSize: numberEnv('LLM_GITHUB_IMPACT_MAX_BATCH_SIZE', 8),
  llmGithubBriefingMaxBatchSize: numberEnv('LLM_GITHUB_BRIEFING_MAX_BATCH_SIZE', 2),
  llmOpenRouterImpactMaxBatchSize: numberEnv('LLM_OPENROUTER_IMPACT_MAX_BATCH_SIZE', 8),
  llmOpenRouterBriefingMaxBatchSize: numberEnv('LLM_OPENROUTER_BRIEFING_MAX_BATCH_SIZE', 2),
  llmOpenRouterFreeRpm: numberEnv('LLM_OPENROUTER_FREE_RPM', 20),
  llmOpenRouterFreeRpd: numberEnv('LLM_OPENROUTER_FREE_RPD', 50),
  llmMinCooldownMs: numberEnv('LLM_MIN_COOLDOWN_MS', 2000),
  llmMaxCooldownMs: numberEnv('LLM_MAX_COOLDOWN_MS', 24 * 60 * 60 * 1000),
  llmRateLimitCooldownMs: numberEnv('LLM_RATE_LIMIT_COOLDOWN_MS', 60000),
  llmDailyRateLimitCooldownMs: numberEnv('LLM_DAILY_RATE_LIMIT_COOLDOWN_MS', 12 * 60 * 60 * 1000),
  llmPayloadTooLargeCooldownMs: numberEnv('LLM_PAYLOAD_TOO_LARGE_COOLDOWN_MS', 10 * 60 * 1000),
  llmTransportErrorCooldownMs: numberEnv('LLM_TRANSPORT_ERROR_COOLDOWN_MS', 120000),
  llmBadResponseCooldownMs: numberEnv('LLM_BAD_RESPONSE_COOLDOWN_MS', 120000),
  llmModelErrorCooldownMs: numberEnv('LLM_MODEL_ERROR_COOLDOWN_MS', 30000),
  p0BriefingCategorySlug: process.env.P0_BRIEFING_CATEGORY_SLUG || 'artificial-intelligence',
  p0BriefingRunUntilEmpty: process.env.P0_BRIEFING_RUN_UNTIL_EMPTY === 'true',
  categoryBriefingBatchesPerTick: Number(process.env.CATEGORY_BRIEFING_BATCHES_PER_TICK || 1),
  categoryBriefingConcurrency: Math.max(1, Number(process.env.CATEGORY_BRIEFING_CONCURRENCY || 1)),
  categoryBriefingFreeBatchSize: numberEnv('CATEGORY_BRIEFING_FREE_BATCH_SIZE', 5),
  categoryBriefingOpenAiBatchSize: numberEnv('CATEGORY_BRIEFING_OPENAI_BATCH_SIZE', 10),
  categoryBriefingExcludeLevels: listEnv('CATEGORY_BRIEFING_EXCLUDE_LEVELS', []),
  p1BriefingModel: process.env.P1_BRIEFING_MODEL || 'gpt-5-nano',
  p1BriefingBatchSize: Number(process.env.P1_BRIEFING_BATCH_SIZE || 10),
  p1BriefingPollIntervalSeconds: Number(process.env.P1_BRIEFING_POLL_INTERVAL_SECONDS || 300),
  p1BriefingWindowHours: Number(process.env.P1_BRIEFING_WINDOW_HOURS || 168),
  p1BriefingCategorySlug: process.env.P1_BRIEFING_CATEGORY_SLUG || 'artificial-intelligence',
  p1BriefingRunUntilEmpty: process.env.P1_BRIEFING_RUN_UNTIL_EMPTY === 'true',
  p2BriefingModel: process.env.P2_BRIEFING_MODEL || 'gpt-5-nano',
  p2BriefingBatchSize: Number(process.env.P2_BRIEFING_BATCH_SIZE || 20),
  p2BriefingPollIntervalSeconds: Number(process.env.P2_BRIEFING_POLL_INTERVAL_SECONDS || 300),
  p2BriefingWindowHours: Number(process.env.P2_BRIEFING_WINDOW_HOURS || 168),
  p2BriefingCategorySlug: process.env.P2_BRIEFING_CATEGORY_SLUG || 'artificial-intelligence',
  p2BriefingRunUntilEmpty: process.env.P2_BRIEFING_RUN_UNTIL_EMPTY === 'true',
  p3BriefingModel: process.env.P3_BRIEFING_MODEL || 'gpt-5-nano',
  p3BriefingBatchSize: Number(process.env.P3_BRIEFING_BATCH_SIZE || 20),
  p3BriefingPollIntervalSeconds: Number(process.env.P3_BRIEFING_POLL_INTERVAL_SECONDS || 300),
  p3BriefingWindowHours: Number(process.env.P3_BRIEFING_WINDOW_HOURS || 168),
  p3BriefingCategorySlug: process.env.P3_BRIEFING_CATEGORY_SLUG || 'artificial-intelligence',
  p3BriefingRunUntilEmpty: process.env.P3_BRIEFING_RUN_UNTIL_EMPTY === 'true',
  mattermostWebhookUrl: process.env.MATTERMOST_WEBHOOK_URL || '',
  mattermostEnabled: process.env.MATTERMOST_ENABLED !== 'false',
  mattermostPollIntervalSeconds: Number(process.env.MATTERMOST_POLL_INTERVAL_SECONDS || 60),
  mattermostBatchSize: Number(process.env.MATTERMOST_BATCH_SIZE || 10),
  mattermostWindowHours: Number(process.env.MATTERMOST_WINDOW_HOURS || 168),
  mattermostStabilityDelayMinutes: Number(process.env.MATTERMOST_STABILITY_DELAY_MINUTES || 10),
  mattermostProcessingStaleMinutes: Number(process.env.MATTERMOST_PROCESSING_STALE_MINUTES || 10),
  mattermostFailedRetryBackoffMinutes: numberEnv('MATTERMOST_FAILED_RETRY_BACKOFF_MINUTES', 5),
  mattermostRequireCrossCategoryClearance: booleanEnv('MATTERMOST_REQUIRE_CROSS_CATEGORY_CLEARANCE', true),
  mattermostCrossCategoryClearanceMinSimilarity: numberEnv('MATTERMOST_CROSS_CATEGORY_CLEARANCE_MIN_SIMILARITY', 0.68),
  mattermostCategorySlug: process.env.MATTERMOST_CATEGORY_SLUG || 'artificial-intelligence',
  mattermostCategorySlugs: listEnv(
    'MATTERMOST_CATEGORY_SLUGS',
    [process.env.MATTERMOST_CATEGORY_SLUG || 'artificial-intelligence'],
  ),
  mattermostNotifyExisting: process.env.MATTERMOST_NOTIFY_EXISTING === 'true',
  mattermostLevels: (process.env.MATTERMOST_LEVELS || 'P0')
    .split(',')
    .map((level) => level.trim().toUpperCase())
    .filter(Boolean),
  mattermostUsername: process.env.MATTERMOST_USERNAME || 'SignalRSS',
  mattermostIconEmoji: process.env.MATTERMOST_ICON_EMOJI || ':satellite:',
  mattermostChannel: process.env.MATTERMOST_CHANNEL || '',
  mattermostChannelsByCategory: keyValueEnv('MATTERMOST_CHANNELS_BY_CATEGORY'),
  mattermostThumbnailMaxCandidates: Number(process.env.MATTERMOST_THUMBNAIL_MAX_CANDIDATES || 12),
  mattermostGenerateMissingThumbnails: process.env.MATTERMOST_GENERATE_MISSING_THUMBNAILS !== 'false',
  mattermostGeneratedThumbnailModel: process.env.MATTERMOST_GENERATED_THUMBNAIL_MODEL || 'gpt-image-2',
  mattermostGeneratedThumbnailSize: process.env.MATTERMOST_GENERATED_THUMBNAIL_SIZE || '1536x1024',
  mattermostGeneratedThumbnailQuality: process.env.MATTERMOST_GENERATED_THUMBNAIL_QUALITY || 'low',
  mattermostGeneratedThumbnailTimeoutMs: numberEnv('MATTERMOST_GENERATED_THUMBNAIL_TIMEOUT_MS', 45000),
  mattermostGeneratedThumbnailAttempts: numberEnv('MATTERMOST_GENERATED_THUMBNAIL_ATTEMPTS', 3),
  mattermostGeneratedThumbnailBackoffMs: (process.env.MATTERMOST_GENERATED_THUMBNAIL_BACKOFF_MS || '1000,3000,7000')
    .split(',')
    .map((value) => Number(value.trim()))
    .filter((value) => Number.isFinite(value) && value >= 0),
  mattermostImageProvider: process.env.MATTERMOST_IMAGE_PROVIDER || 'openai',
  mattermostImageProviderFallbacks: listEnv('MATTERMOST_IMAGE_PROVIDER_FALLBACKS', [
    process.env.MATTERMOST_IMAGE_PROVIDER || 'openai',
  ]),
  mattermostImageOpenRouterApiKey: process.env.MATTERMOST_IMAGE_OPENROUTER_API_KEY || '',
  mattermostImageOpenRouterModel: process.env.MATTERMOST_IMAGE_OPENROUTER_MODEL || 'google/gemini-2.5-flash-image',
  mattermostImageOpenRouterReferer: process.env.MATTERMOST_IMAGE_OPENROUTER_REFERER || '',
  mattermostImageOpenRouterTitle: process.env.MATTERMOST_IMAGE_OPENROUTER_TITLE || 'SignalRSS',
  mattermostImageNvidiaApiKey: process.env.MATTERMOST_IMAGE_NVIDIA_API_KEY || process.env.NVIDIA_API_KEY || '',
  mattermostImageNvidiaEndpoint: process.env.MATTERMOST_IMAGE_NVIDIA_ENDPOINT || 'https://ai.api.nvidia.com/v1/genai/black-forest-labs/flux.2-klein-4b',
  mattermostImageNvidiaModel: process.env.MATTERMOST_IMAGE_NVIDIA_MODEL || 'black-forest-labs/flux.2-klein-4b',
  mattermostImageNvidiaWidth: numberEnv('MATTERMOST_IMAGE_NVIDIA_WIDTH', 1344),
  mattermostImageNvidiaHeight: numberEnv('MATTERMOST_IMAGE_NVIDIA_HEIGHT', 768),
  mattermostImageNvidiaSteps: numberEnv('MATTERMOST_IMAGE_NVIDIA_STEPS', 4),
  mattermostGeneratedThumbnailDir: process.env.MATTERMOST_GENERATED_THUMBNAIL_DIR || '/app/data/generated-thumbnails',
  mattermostGeneratedThumbnailPublicPath: process.env.MATTERMOST_GENERATED_THUMBNAIL_PUBLIC_PATH || '/generated-thumbnails',
  mattermostImageUploadEnabled: process.env.MATTERMOST_IMAGE_UPLOAD_ENABLED !== 'false',
  mattermostImageUploadProvider: process.env.MATTERMOST_IMAGE_UPLOAD_PROVIDER || 'litterbox',
  mattermostImageUploadEndpoint: process.env.MATTERMOST_IMAGE_UPLOAD_ENDPOINT || 'https://litterbox.catbox.moe/resources/internals/api.php',
  mattermostImageUploadExpiration: process.env.MATTERMOST_IMAGE_UPLOAD_EXPIRATION || '72h',
  mattermostImageUploadAttempts: Number(process.env.MATTERMOST_IMAGE_UPLOAD_ATTEMPTS || 3),
  mattermostImageUploadBackoffMs: (process.env.MATTERMOST_IMAGE_UPLOAD_BACKOFF_MS || '1000,3000,7000')
    .split(',')
    .map((value) => Number(value.trim()))
    .filter((value) => Number.isFinite(value) && value >= 0),
  crossCategoryAdjudicationModel: process.env.CROSS_CATEGORY_ADJUDICATION_MODEL || 'gpt-5-nano',
  crossCategoryAdjudicationBatchSize: Number(process.env.CROSS_CATEGORY_ADJUDICATION_BATCH_SIZE || 1),
  crossCategoryAdjudicationPollIntervalSeconds: Number(process.env.CROSS_CATEGORY_ADJUDICATION_POLL_INTERVAL_SECONDS || 300),
  crossCategoryAdjudicationWindowHours: Number(process.env.CROSS_CATEGORY_ADJUDICATION_WINDOW_HOURS || 168),
  crossCategoryAdjudicationSeedWindowHours: Number(process.env.CROSS_CATEGORY_ADJUDICATION_SEED_WINDOW_HOURS || 1),
  crossCategoryAdjudicationCategories: (process.env.CROSS_CATEGORY_ADJUDICATION_CATEGORIES || 'artificial-intelligence,cybersecurity,cloud-infrastructure,semiconductors,software-development,consumer-electronics,gaming,enterprise-technology,startups-venture-capital,policy-regulation,science-research,automotive-mobility,fintech-crypto,crypto-web3')
    .split(',')
    .map((slug) => slug.trim())
    .filter(Boolean),
  crossCategoryAdjudicationLevels: (process.env.CROSS_CATEGORY_ADJUDICATION_LEVELS || 'P0,P1,P2,P3')
    .split(',')
    .map((level) => level.trim().toUpperCase())
    .filter(Boolean),
  crossCategoryAdjudicationMinCentroidSimilarity: Number(process.env.CROSS_CATEGORY_ADJUDICATION_MIN_CENTROID_SIMILARITY || 0.76),
  crossCategoryAdjudicationArticleScanMinCentroidSimilarity: Number(process.env.CROSS_CATEGORY_ADJUDICATION_ARTICLE_SCAN_MIN_CENTROID_SIMILARITY || 0.68),
  crossCategoryAdjudicationMinArticleSimilarity: Number(process.env.CROSS_CATEGORY_ADJUDICATION_MIN_ARTICLE_SIMILARITY || 0.80),
  crossCategoryAdjudicationMinTokenOverlap: Number(process.env.CROSS_CATEGORY_ADJUDICATION_MIN_TOKEN_OVERLAP || 2),
  crossCategoryAdjudicationMaxTokenFanout: Number(process.env.CROSS_CATEGORY_ADJUDICATION_MAX_TOKEN_FANOUT || 120),
  crossCategoryAdjudicationVectorNeighbors: Number(process.env.CROSS_CATEGORY_ADJUDICATION_VECTOR_NEIGHBORS || 30),
  priorityAdjudicationVectorNeighbors: Number(process.env.PRIORITY_ADJUDICATION_VECTOR_NEIGHBORS || 40),
  priorityAdjudicationMinStrongTokenOverlap: Number(process.env.PRIORITY_ADJUDICATION_MIN_STRONG_TOKEN_OVERLAP || 2),
  crossCategoryAdjudicationMergeConfidence: Number(process.env.CROSS_CATEGORY_ADJUDICATION_MERGE_CONFIDENCE || 0.78),
  crossCategoryAdjudicationApplyMerges: process.env.CROSS_CATEGORY_ADJUDICATION_APPLY_MERGES === 'true',
  crossCategoryAdjudicationRunUntilEmpty: process.env.CROSS_CATEGORY_ADJUDICATION_RUN_UNTIL_EMPTY === 'true',
  langfusePublicKey: process.env.LANGFUSE_PUBLIC_KEY || '',
  langfuseSecretKey: process.env.LANGFUSE_SECRET_KEY || '',
  langfuseBaseUrl: process.env.LANGFUSE_BASE_URL || 'https://cloud.langfuse.com',
};
